# SPDX-FileCopyrightText: Copyright (c) 2009-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/java
readers:
  - "urn:github:526301"
install: |-
  sudo /usr/bin/install-postgres.sh
  pdd -f /dev/null
  bundle install --no-color
merge:
  script: |-
    bundle exec rake
