<!--
 * netbout.com
 *
 * Redistribution and use in source and binary forms, with or 
 * without modification, are PROHIBITED without prior written 
 * permission from the author. This product may NOT be used 
 * anywhere and on any computer except the server platform of 
 * netbout.com. located at www.netbout.com. If you received this 
 * code occasionally and without intent to use it, please report 
 * this incident to the author by email: privacy@netbout.com
 *
 * @author Yegor Bugayenko <yegor256@yahoo.com>
 * @copyright Copyright (c) netbout.com, 2010
 * @version $Id$
 -->

<? $this->includeCSS('bout.css') ?>

<div class="preamble">
    <div class="title">New PHP project, lead engineer wanted..</div>

    <table class="details" cellpadding="0" cellspacing="0">
        <tr><td>
            <span><?=_t('Started on')?>:</span>
            <?=Zend_Date::now()->sub(rand(10, 50), Zend_Date::DAY)->get(Zend_Date::DATE_MEDIUM)?>
            (2 weeks ago)
        </td></tr>
    </table>

    <div class="participants">
        <? foreach (array(1, 2, 3, 4, 5, 6) as $i): ?>
            <a href="" title="<?=_t('filter by him/her')?>">
                <? if (rand(0, 1)): ?>
                    <img src="http://www.robert-deniro.com/deniro.jpg"/>
                <? else: ?>
                    <span class="anonymous">John Smith</span>
                <? endif; ?>
            </a>
        <? endforeach; ?>
        <form action="?p=bout" method="post" class="inline">
            <dd><input type="text" size="50" value="john13@example.com"/></dd>
            <dd><input type="submit" value="Invite" /></dd>
        </form>
    </div>

    <div class="tags">
        <ul>
            <? foreach (array('PHP', 'C++', 'netbout', 'Germany', 'USA') as $i): ?>
                <li class="tag"><a href=""><?=$i?></a></li>
            <? endforeach; ?>
        </ul>
        <form action="?p=bout" method="post" class="inline">
            <dd><input type="text" size="20" value=""/></dd>
            <dd><input type="submit" value="Add" /></dd>
        </form>
    </div>

    <div class="stages">
        <ul>
            <? foreach (array('questionnaire', 'test task', 'UML drawing') as $i): ?>
                <li class="stage"><a href=""><?=$i?></a></li>
            <? endforeach; ?>
        </ul>
    </div>
</div>

<? for ($i = 0; $i < 5; $i++): ?>
    <div class="message">
        <div class="author">
            <img src="http://www.robert-deniro.com/deniro.jpg" />
        </div>
        <div class="heading">
            <?=_t('%s ago by %s', '5 days', 'peter898')?>
        </div>
        <div class="text">
            <? for ($j = 0; $j < rand(1,3); $j++): ?>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <? endfor; ?>
        </div>
    </div>
<? endfor; ?>

<div class="reply">
    <form action="?p=bout" method="post">
        <dd><textarea onkeyup="$('#preview').html($('#reply').val());" id="reply"></textarea></dd>
        <div id="preview"></div>
        <dd><input type="submit" value="<?=_t('Post Your Message')?>" /></dd>
    </form>
</div>
