<!--
 * netbout.com
 *
 * Redistribution and use in source and binary forms, with or 
 * without modification, are PROHIBITED without prior written 
 * permission from the author. This product may NOT be used 
 * anywhere and on any computer except the server platform of 
 * netbout.com. located at www.netbout.com. If you received this 
 * code occasionally and without intent to use it, please report 
 * this incident to the author by email: privacy@netbout.com
 *
 * @author Yegor Bugayenko <yegor256@yahoo.com>
 * @copyright Copyright (c) netbout.com, 2010
 * @version $Id: build.xml 3 2010-04-23 21:02:37Z yegor256@yahoo.com $
 -->

<? $this->includeCSS('front.css') ?>

<div class="filter">
    <b>Filtered by</b> (click to remove):
    <ul>
        <li class="tag"><a href="" title="don't filter by PHP">PHP</a></li>
        <li><a href="" title="don't filter by Ales Solodov">Alex Solodov</a></li>
    </ul>
</div>

<? for ($intro = 0; $intro < 5; $intro++): ?>
    <div class="intro">
        <div class="participants">
            <? foreach (array(1, 2, 3, 4, 5, 6) as $i): ?>
                <a href="" title="filter by him/her">
                    <? if (rand(0, 1)): ?>
                        <img src="img/<?=$i?>.jpg"/>
                    <? else: ?>
                        <span class="anonymous">John Smith</span>
                    <? endif; ?>
                </a>
            <? endforeach; ?>
        </div>
        <a href="<?=$this->url(array('bout'=>3), 'bout')?>" class="title <?=($intro < 2 ? 'unread' : false)?>">
            #<?=rand(1,999)?>: New project in PHP, lead developer wanted..
        </a><br/>
        <?=$intro * 2 + 3?> days ago by <a href="" title="filter by this user">John Smith</a>: 
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        <ul class="tags">
            <? foreach (array('PHP', 'C++', 'netbout', 'Germany', 'USA') as $i): ?>
                <li class="tag"><a href=""><?=$i?></a></li>
            <? endforeach; ?>
        </ul>
    </div>
<? endfor; ?>
    