<h1>Start New</h1>

<p>Start new <b>bout</b>:</p>

<?=$this->forma()
    ->addBehavior('flash', "'bout started'")
    ->addBehavior('redirect')
    ->addField('text', 'id')
        ->fieldLabel('Email or netBout ID of your first recipient')
        ->fieldAttrib('size', 12)
        ->fieldAttrib('maxlength', 7)
        ->fieldAttrib('disabled', 'disabled')
        ->fieldValue('john13')
    ->addField('text', 'subject')
        ->fieldLabel('Subject')
        ->fieldAttrib('size', 50)
        ->fieldAttrib('maxlength', 200)
    ->addField('submit')
        ->fieldValue('Start New Bout')
        // ->fieldAction(false) // to be changed
    ?>

