<?php
    $this->headMeta()
        ->appendHttpEquiv('expires', 'Wed, 26 Feb 1997 08:21:57 GMT')
        ->appendHttpEquiv('pragma', 'no-cache')
        ->appendHttpEquiv('Cache-Control', 'no-cache')
        ->appendName('keywords', '')
        ->appendName('description', '');

    $this->includeCSS('global.css');

?><?php echo $this->doctype()?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
    <?php echo $this->headTitle()?>
    <?php echo $this->headMeta()?>
    <?php echo $this->headLink()?>
    <?php echo $this->headStyle()?>
</head> 
<body>

    <div>
    <?php echo  $this->layout()->content ?>
    </div>

</body>
</html>
