<?="<?xml version=\"1.0\" encoding=\"utf-8\"?>"?>
<!--
 * netbout.com
 *
 * Redistribution and use in source and binary forms, with or 
 * without modification, are PROHIBITED without prior written 
 * permission from the author. This product may NOT be used 
 * anywhere and on any computer except the server platform of 
 * netbout.com. located at www.netbout.com. If you received this 
 * code occasionally and without intent to use it, please report 
 * this incident to the author by email: privacy@netbout.com
 *
 * @author Yegor Bugayenko <yegor256@yahoo.com>
 * @copyright Copyright (c) netbout.com, 2010
 * @version $Id$
 -->
<? $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8') ?>
<? $this->includeCSS('global.css') ?>
<? $this->includeJQuery() ?>
<? $this->headScript()->appendFile('http://jquery-ui.googlecode.com/svn/tags/1.8rc3/ui/jquery-ui.js') ?>
<?=$this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
    <?=$this->headTitle()?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
</head>
<body>
    <div id="header">
        <div class="wrapper">
            <table cellpadding="0" cellspacing="0">
                <tr><td class="logo">
                    <a id="logo" href="<?=$this->url(array(), 'front')?>"><img src="<?=$this->viewFile('logo.png')?>"/></a>
                    <ul>
                        <li><a href="<?=$this->url(array('action'=>'account'), 'user')?>" 
                            style="font-weight: bolder;">john13</a></li>
                        <li><a href="<?=$this->url(array(), 'start')?>"><?=_t('start')?></a></li>
                        <li><a href="<?=$this->url(array('action'=>'login'), 'user')?>"><?=_t('log out')?></a></li>
                    </ul>
                </td>
                <td align="right">
                    <form action="" method="post">
                        <dd><input type="text" value="PHP Germany" size="46" autocomplete="off" /></dd>
                        <dd><input type="submit" value="?" /></dd>
                    </form>
                </td></tr>
            </table>
        </div>
    </div>
    <div id="content">
        <div class="wrapper">
            <?=$this->flashMessage()?>
            <?=$this->layout()->content?>
        </div>
    </div>
    <div id="footer">
        <div class="wrapper">
            <ul id="menu">
                <li><a href=""><?=_t('how it works')?></a></li>
                <li><a href=""><?=_t('your privacy')?></a></li>
                <li><a href=""><?=_t('feedback')?></a></li>
            </ul>
            <p>(c) <?=Zend_Date::now()->get(Zend_Date::YEAR)?>, netBout.com,
                rev.<?=FaZend_Revision::get()?>, 
                <?=$this->pageLoadTime()?>, 
                <?=_t('All Rights Reserved')?>.
            </p>
        </div>
    </div>
    <?//=$this->googleAnalytics(false)?>
    <?=$this->headScript() ?>
</body>
</html>
