<!--
 * netbout.com
 *
 * Redistribution and use in source and binary forms, with or 
 * without modification, are PROHIBITED without prior written 
 * permission from the author. This product may NOT be used 
 * anywhere and on any computer except the server platform of 
 * netbout.com. located at www.netbout.com. If you received this 
 * code occasionally and without intent to use it, please report 
 * this incident to the author by email: privacy@netbout.com
 *
 * @author Yegor Bugayenko <yegor256@yahoo.com>
 * @copyright Copyright (c) netbout.com, 2010
 * @version $Id$
 -->
<?php echo $this->doctype()?>
<?php
    $this->headMeta()
        ->appendHttpEquiv('expires', 'Wed, 26 Feb 1997 08:21:57 GMT')
        ->appendHttpEquiv('pragma', 'no-cache')
        ->appendHttpEquiv('Cache-Control', 'no-cache')
        ->appendName('keywords', '')
        ->appendName('description', '');

    $this->includeCSS('global.css');

?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
    <?php echo $this->headTitle()?>
    <?php echo $this->headMeta()?>
    <?php echo $this->headLink()?>
    <?php echo $this->headStyle()?>
</head> 
<body>

    <div>
    <?php echo  $this->layout()->content ?>
    </div>

</body>
</html>
