
<h1>Account Settings</h1>

<p>Your account:</p>

<?=$this->forma()
    ->addBehavior('flash', "'changes were saved'")
    ->addBehavior('redirect')
    ->addField('text', 'id')
        ->fieldLabel('Your netBout ID (can\'t be changed)')
        ->fieldAttrib('size', 12)
        ->fieldAttrib('maxlength', 7)
        ->fieldAttrib('disabled', 'disabled')
        ->fieldValue('john13')
    ->addField('text', 'password')
        ->fieldLabel('New password (email confirmation will be required)')
        ->fieldAttrib('type', 'password')
        ->fieldAttrib('size', 22)
        ->fieldAttrib('maxlength', 100)
    ->addField('submit')
        ->fieldValue('Save Changes')
        ->fieldAction(false) // to be changed
    ?>

