<!--
 * netbout.com
 *
 * Redistribution and use in source and binary forms, with or 
 * without modification, are PROHIBITED without prior written 
 * permission from the author. This product may NOT be used 
 * anywhere and on any computer except the server platform of 
 * netbout.com. located at www.netbout.com. If you received this 
 * code occasionally and without intent to use it, please report 
 * this incident to the author by email: privacy@netbout.com
 *
 * @author Yegor Bugayenko <yegor256@yahoo.com>
 * @copyright Copyright (c) netbout.com, 2010
 * @version $Id$
 -->

<h1><?=_t('Account Settings')?></h1>

<p><?=_t('Your account')?>:</p>

<?=$this->forma()
    ->addBehavior('flash', "_t('changes were saved')")
    ->addBehavior('redirect')
    ->addField('text', 'id')
        ->fieldLabel(_t('Your netBout ID (can\'t be changed)'))
        ->fieldAttrib('size', 12)
        ->fieldAttrib('maxlength', 7)
        ->fieldAttrib('disabled', 'disabled')
        ->fieldValue('john13')
    ->addField('text', 'password')
        ->fieldLabel(_t('New password (email confirmation will be required)'))
        ->fieldAttrib('type', 'password')
        ->fieldAttrib('size', 22)
        ->fieldAttrib('maxlength', 100)
    ->addField('submit')
        ->fieldValue(_t('Save Changes'))
        ->fieldAction(false) // to be changed
    ?>

