
<p>Before we let you in we have to authenticate your 
    identity, in order to protect your private and sensitive
    information.</p>

<?=$this->forma()
    ->addBehavior('flash', "'logged in'")
    ->addField('text', 'id')
        ->fieldLabel('Your NetBout ID')
        ->fieldAttrib('size', 12)
        ->fieldAttrib('maxlength', 7)
    ->addField('text', 'password')
        ->fieldLabel('Password')
        ->fieldAttrib('type', 'password')
        ->fieldAttrib('size', 22)
        ->fieldAttrib('maxlength', 100)
    ->addField('submit')
        ->fieldValue('Login')
        ->fieldAction(false) // to be changed
    ?>
