<!--
 * netbout.com
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are PROHIBITED without prior written
 * permission from the author. This product may NOT be used
 * anywhere and on any computer except the server platform of
 * netbout.com. located at www.netbout.com. If you received this
 * code occasionally and without intent to use it, please report
 * this incident to the author by email: privacy@netbout.com
 *
 * @author Yegor Bugayenko <yegor256@yahoo.com>
 * @copyright Copyright (c) netbout.com, 2010
 * @version $Id$
 -->

<h1><?=_t('Login')?></h1>

<p><?=_t('Before we let you in we have to authenticate your
    identity, in order to protect your private and sensitive
    information.')?></p>

<?=$this->forma()
    ->addBehavior('flash', "_t('logged in')")
    ->addBehavior('redirect')
    ->addField('text', 'id')
        ->fieldLabel(_t('Your NetBout ID'))
        ->fieldAttrib('size', 12)
        ->fieldAttrib('maxlength', 7)
    ->addField('text', 'password')
        ->fieldLabel(_t('Password'))
        ->fieldAttrib('type', 'password')
        ->fieldAttrib('size', 22)
        ->fieldAttrib('maxlength', 100)
    ->addField('submit')
        ->fieldValue(_t('Login'))
        ->fieldAction(false) // to be changed
    ?>
