<?="<?xml version=\"1.0\" encoding=\"utf-8\"?>"?>
<!DOCTYPE html PUBLIC 
    "-//W3C//DTD XHTML 1.0 Strict//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
    <title>netbout.com prototype</title>
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
    <style type="text/css">
    <?
    // tpc2.com colors
    define('TPC_DARKGRAY', '#5a5a5a');
    define('TPC_GRAY', '#7d8f9b');
    define('TPC_LIGHTGRAY', '#e7e9ea');
    define('TPC_BLACK', '#122632');
    define('TPC_BLUE', '#0093d0');
    define('TPC_RED', '#e31b23');
    define('TPC_GREEN', '#54b948');
    define('TPC_ORANGE', 'orange');
    define('TPC_YELLOW', '#fff454');
    define('TPC_WHITE', '#ffffff');

    // fazend blue colors
    define('FZ_BLUE1', '#062B35'); // dark blue, almost black
    define('FZ_BLUE2', '#134558'); // dark blue, in logo
    define('FZ_BLUE3', '#2276A4'); // blue, in logo
    define('FZ_BLUE4', '#92BECE'); // light blue
    ?>
    <? include 'css/global.css' ?>
    <? include 'css/front.css' ?>
    <? include 'css/bout.css' ?>
    </style>
</head> 
<body>
    <div id="header">
        <div class="wrapper">
            <table cellpadding="0" cellspacing="0">
                <tr><td class="logo">
                    <a id="logo" href="?p=front"><img src="logo.png"/></a>
                    <ul>
                        <li><a href="?p=account" style="font-weight: bolder;">john13</a></li>
                        <li><a href="?p=start">start</a></li>
                        <li><a href="?p=login">log out</a></li>
                    </ul>
                </td>
                <td align="right">
                    <form action="" method="post">
                        <dd><input type="text" value="PHP Germany" size="46" autocomplete="off" /></dd>
                        <dd><input type="submit" value="?" /></dd>
                    </form>
                </td></tr>
            </table>
        </div>
    </div>
    <div id="content">
        <div class="wrapper">
            <? include 'scripts/' . $page . '.phtml' ?>
        </div>
    </div>
    <div id="footer">
        <div class="wrapper">
            <ul id="menu">
                <li><a href="">how it works</a></li>
                <li><a href="">your privacy</a></li>
                <li><a href="">feedback</a></li>
            </ul>
            <p>(c) 2010, netBout.com, All Rights Reserved.</p>
        </div>
    </div>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
    <script type="text/javascript" src="http://jquery-ui.googlecode.com/svn/tags/1.8rc3/ui/jquery-ui.js"></script>
    <script type="text/javascript">//<![CDATA[
        $(document).ready(
            function()
            {
                $('#topsearch__keyword').autocomplete(
                    {
                        source: function(request, response)
                        {
                            $.post('/york/index/autocomplete', $.extend(postData, request), response, 'json');
                        },
                        minLength: 2
                    }
                );
            }
        );
        $(document).ready(
            function()
            {
                $("div#content-wrapper > ul.menu li").hover(
                    function() { $("> ul", this).show() },
                    function() { $("> ul", this).hide() }
                )
            }
        )
    //]]></script>    
</body>
</html>
